# Generated by Django 5.2.12 on 2026-03-31 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0002_phase1_customer_project_reports"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("PM", "Project Manager"),
                            ("TESTER", "Tester"),
                            ("QA", "QA"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="asset",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="batch",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="asset",
            name="criticality",
        ),
        migrations.RemoveField(
            model_name="asset",
            name="value",
        ),
        migrations.AddField(
            model_name="asset",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="environment",
            field=models.CharField(
                choices=[("prod", "Production"), ("test", "Test"), ("uat", "UAT")],
                default="test",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="fqdn",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="owner",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="asset",
            name="tags_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="asset",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("host", "Host"),
                    ("domain", "Domain"),
                    ("url", "URL"),
                    ("app", "App"),
                    ("api", "API"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("in_review", "In Review"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="test_type",
            field=models.CharField(
                choices=[
                    ("web", "Web"),
                    ("app", "App"),
                    ("api", "API"),
                    ("internal", "Internal"),
                    ("external", "External"),
                ],
                default="web",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["project", "asset_type", "environment"],
                name="business_as_project_8c56fb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["customer", "status", "test_type"],
                name="business_pr_custome_6e3116_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.UniqueConstraint(
                fields=("project", "name"), name="uniq_asset_name_per_project"
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="business.project",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmember",
            constraint=models.UniqueConstraint(
                fields=("project", "user", "member_type"),
                name="uniq_project_member_type",
            ),
        ),
    ]
