# Generated by Django 5.2.12 on 2026-03-31 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0003_projectmember_alter_asset_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("nessus", "Nessus"),
                            ("awvs", "AWVS"),
                            ("burp", "Burp"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("fixed", "Fixed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("finding_type", models.CharField(blank=True, max_length=100)),
                ("external_id", models.CharField(blank=True, max_length=120)),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.CharField(blank=True, max_length=50)),
                ("protocol", models.CharField(blank=True, max_length=20)),
                ("url", models.URLField(blank=True)),
                ("parameter", models.CharField(blank=True, max_length=255)),
                ("cve_list", models.JSONField(blank=True, default=list)),
                ("cwe_list", models.JSONField(blank=True, default=list)),
                ("description_html", models.TextField(blank=True)),
                ("risk_html", models.TextField(blank=True)),
                ("remediation_html", models.TextField(blank=True)),
                ("evidence_html", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoryFinding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_title", models.CharField(max_length=255)),
                (
                    "snapshot_severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                            ("info", "Info"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "snapshot_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("fixed", "Fixed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("snapshot_data_json", models.JSONField(blank=True, default=dict)),
                ("snapshot_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScanFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("nessus", "Nessus"),
                            ("awvs", "AWVS"),
                            ("burp", "Burp XML"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parser_type", models.CharField(blank=True, max_length=50)),
                ("storage_key", models.CharField(max_length=500)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("parsing", "Parsing"),
                            ("parsed", "Parsed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("parse_summary", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="batch",
            name="extra",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="finished_at",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="scheduled_at",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="started_at",
        ),
        migrations.AddField(
            model_name="batch",
            name="batch_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="scope_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("testing", "Testing"),
                    ("qa_review", "QA Review"),
                    ("pm_review", "PM Review"),
                    ("reported", "Reported"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="batch",
            index=models.Index(
                fields=["asset", "status", "start_date"],
                name="business_ba_asset_i_6ac7df_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="batch",
            constraint=models.UniqueConstraint(
                fields=("asset", "batch_no"), name="uniq_batch_no_per_asset"
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="findings",
                to="business.asset",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="findings",
                to="business.batch",
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_findings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_findings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historyfinding",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_findings",
                to="business.asset",
            ),
        ),
        migrations.AddField(
            model_name="historyfinding",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_findings",
                to="business.batch",
            ),
        ),
        migrations.AddField(
            model_name="historyfinding",
            name="finding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history_snapshots",
                to="business.finding",
            ),
        ),
        migrations.AddField(
            model_name="scanfile",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_files",
                to="business.batch",
            ),
        ),
        migrations.AddField(
            model_name="scanfile",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="finding",
            name="source_scan_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="findings",
                to="business.scanfile",
            ),
        ),
    ]
