# Generated by Django 5.2.12 on 2026-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "business",
            "0004_finding_historyfinding_scanfile_remove_batch_extra_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="batch",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reporttemplate",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
